### ISSUE TITLE
Verify Email

### ISSUE THREAD

**Issue by tambui142** [kyleb13/MobileAppsGroup1#44] opened 2018-11-06 04:25 UTC
Duplicate of #49

**Comment by sam2b** [comment] 2018-11-06 06:13
What exactly do you need to verify?  Only that the email address exists?  Please let me know how I can help.

**Comment by sam2b** [comment] 2018-11-07 07:50
@tambui142 , Kevin is working on this. @nguyek

**Comment by sam2b** [comment] 2018-11-07 07:56
Duplicate of #49

**Closed** 2018-11-09 06:19 UTC
Labels: duplicate
